/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as EngineerRouteImport } from './routes/engineer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EngineerIndexRouteImport } from './routes/engineer.index'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerRoute = EngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerIndexRoute = EngineerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EngineerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engineer': typeof EngineerRouteWithChildren
  '/training': typeof TrainingRoute
  '/engineer/': typeof EngineerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/training': typeof TrainingRoute
  '/engineer': typeof EngineerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/engineer': typeof EngineerRouteWithChildren
  '/training': typeof TrainingRoute
  '/engineer/': typeof EngineerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/engineer' | '/training' | '/engineer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/training' | '/engineer'
  id: '__root__' | '/' | '/engineer' | '/training' | '/engineer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngineerRoute: typeof EngineerRouteWithChildren
  TrainingRoute: typeof TrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer': {
      id: '/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof EngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/': {
      id: '/engineer/'
      path: '/'
      fullPath: '/engineer/'
      preLoaderRoute: typeof EngineerIndexRouteImport
      parentRoute: typeof EngineerRoute
    }
  }
}

interface EngineerRouteChildren {
  EngineerIndexRoute: typeof EngineerIndexRoute
}

const EngineerRouteChildren: EngineerRouteChildren = {
  EngineerIndexRoute: EngineerIndexRoute,
}

const EngineerRouteWithChildren = EngineerRoute._addFileChildren(
  EngineerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngineerRoute: EngineerRouteWithChildren,
  TrainingRoute: TrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
