/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as EngineerRouteImport } from './routes/engineer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EngineerIndexRouteImport } from './routes/engineer.index'
import { Route as EngineerProjectsRouteImport } from './routes/engineer.projects'
import { Route as EngineerComplianceRouteImport } from './routes/engineer.compliance'
import { Route as EngineerCalculationsRouteImport } from './routes/engineer.calculations'
import { Route as EngineerBasisRouteImport } from './routes/engineer.basis'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerRoute = EngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerIndexRoute = EngineerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerProjectsRoute = EngineerProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerComplianceRoute = EngineerComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerCalculationsRoute = EngineerCalculationsRouteImport.update({
  id: '/calculations',
  path: '/calculations',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerBasisRoute = EngineerBasisRouteImport.update({
  id: '/basis',
  path: '/basis',
  getParentRoute: () => EngineerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engineer': typeof EngineerRouteWithChildren
  '/training': typeof TrainingRoute
  '/engineer/basis': typeof EngineerBasisRoute
  '/engineer/calculations': typeof EngineerCalculationsRoute
  '/engineer/compliance': typeof EngineerComplianceRoute
  '/engineer/projects': typeof EngineerProjectsRoute
  '/engineer/': typeof EngineerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/training': typeof TrainingRoute
  '/engineer/basis': typeof EngineerBasisRoute
  '/engineer/calculations': typeof EngineerCalculationsRoute
  '/engineer/compliance': typeof EngineerComplianceRoute
  '/engineer/projects': typeof EngineerProjectsRoute
  '/engineer': typeof EngineerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/engineer': typeof EngineerRouteWithChildren
  '/training': typeof TrainingRoute
  '/engineer/basis': typeof EngineerBasisRoute
  '/engineer/calculations': typeof EngineerCalculationsRoute
  '/engineer/compliance': typeof EngineerComplianceRoute
  '/engineer/projects': typeof EngineerProjectsRoute
  '/engineer/': typeof EngineerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/engineer'
    | '/training'
    | '/engineer/basis'
    | '/engineer/calculations'
    | '/engineer/compliance'
    | '/engineer/projects'
    | '/engineer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/training'
    | '/engineer/basis'
    | '/engineer/calculations'
    | '/engineer/compliance'
    | '/engineer/projects'
    | '/engineer'
  id:
    | '__root__'
    | '/'
    | '/engineer'
    | '/training'
    | '/engineer/basis'
    | '/engineer/calculations'
    | '/engineer/compliance'
    | '/engineer/projects'
    | '/engineer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngineerRoute: typeof EngineerRouteWithChildren
  TrainingRoute: typeof TrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer': {
      id: '/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof EngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/': {
      id: '/engineer/'
      path: '/'
      fullPath: '/engineer/'
      preLoaderRoute: typeof EngineerIndexRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/projects': {
      id: '/engineer/projects'
      path: '/projects'
      fullPath: '/engineer/projects'
      preLoaderRoute: typeof EngineerProjectsRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/compliance': {
      id: '/engineer/compliance'
      path: '/compliance'
      fullPath: '/engineer/compliance'
      preLoaderRoute: typeof EngineerComplianceRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/calculations': {
      id: '/engineer/calculations'
      path: '/calculations'
      fullPath: '/engineer/calculations'
      preLoaderRoute: typeof EngineerCalculationsRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/basis': {
      id: '/engineer/basis'
      path: '/basis'
      fullPath: '/engineer/basis'
      preLoaderRoute: typeof EngineerBasisRouteImport
      parentRoute: typeof EngineerRoute
    }
  }
}

interface EngineerRouteChildren {
  EngineerBasisRoute: typeof EngineerBasisRoute
  EngineerCalculationsRoute: typeof EngineerCalculationsRoute
  EngineerComplianceRoute: typeof EngineerComplianceRoute
  EngineerProjectsRoute: typeof EngineerProjectsRoute
  EngineerIndexRoute: typeof EngineerIndexRoute
}

const EngineerRouteChildren: EngineerRouteChildren = {
  EngineerBasisRoute: EngineerBasisRoute,
  EngineerCalculationsRoute: EngineerCalculationsRoute,
  EngineerComplianceRoute: EngineerComplianceRoute,
  EngineerProjectsRoute: EngineerProjectsRoute,
  EngineerIndexRoute: EngineerIndexRoute,
}

const EngineerRouteWithChildren = EngineerRoute._addFileChildren(
  EngineerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngineerRoute: EngineerRouteWithChildren,
  TrainingRoute: TrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
