/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as EngineerRouteImport } from './routes/engineer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EngineerIndexRouteImport } from './routes/engineer.index'
import { Route as EngineerWorkflowRouteImport } from './routes/engineer.workflow'
import { Route as EngineerReviewRouteImport } from './routes/engineer.review'
import { Route as EngineerReportsRouteImport } from './routes/engineer.reports'
import { Route as EngineerProjectsRouteImport } from './routes/engineer.projects'
import { Route as EngineerIntegrityRouteImport } from './routes/engineer.integrity'
import { Route as EngineerComplianceRouteImport } from './routes/engineer.compliance'
import { Route as EngineerCodesRouteImport } from './routes/engineer.codes'
import { Route as EngineerCalculationsRouteImport } from './routes/engineer.calculations'
import { Route as EngineerBasisRouteImport } from './routes/engineer.basis'
import { Route as EngineerAuditRouteImport } from './routes/engineer.audit'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerRoute = EngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerIndexRoute = EngineerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerWorkflowRoute = EngineerWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerReviewRoute = EngineerReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerReportsRoute = EngineerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerProjectsRoute = EngineerProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerIntegrityRoute = EngineerIntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerComplianceRoute = EngineerComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerCodesRoute = EngineerCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerCalculationsRoute = EngineerCalculationsRouteImport.update({
  id: '/calculations',
  path: '/calculations',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerBasisRoute = EngineerBasisRouteImport.update({
  id: '/basis',
  path: '/basis',
  getParentRoute: () => EngineerRoute,
} as any)
const EngineerAuditRoute = EngineerAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => EngineerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engineer': typeof EngineerRouteWithChildren
  '/training': typeof TrainingRoute
  '/engineer/audit': typeof EngineerAuditRoute
  '/engineer/basis': typeof EngineerBasisRoute
  '/engineer/calculations': typeof EngineerCalculationsRoute
  '/engineer/codes': typeof EngineerCodesRoute
  '/engineer/compliance': typeof EngineerComplianceRoute
  '/engineer/integrity': typeof EngineerIntegrityRoute
  '/engineer/projects': typeof EngineerProjectsRoute
  '/engineer/reports': typeof EngineerReportsRoute
  '/engineer/review': typeof EngineerReviewRoute
  '/engineer/workflow': typeof EngineerWorkflowRoute
  '/engineer/': typeof EngineerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/training': typeof TrainingRoute
  '/engineer/audit': typeof EngineerAuditRoute
  '/engineer/basis': typeof EngineerBasisRoute
  '/engineer/calculations': typeof EngineerCalculationsRoute
  '/engineer/codes': typeof EngineerCodesRoute
  '/engineer/compliance': typeof EngineerComplianceRoute
  '/engineer/integrity': typeof EngineerIntegrityRoute
  '/engineer/projects': typeof EngineerProjectsRoute
  '/engineer/reports': typeof EngineerReportsRoute
  '/engineer/review': typeof EngineerReviewRoute
  '/engineer/workflow': typeof EngineerWorkflowRoute
  '/engineer': typeof EngineerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/engineer': typeof EngineerRouteWithChildren
  '/training': typeof TrainingRoute
  '/engineer/audit': typeof EngineerAuditRoute
  '/engineer/basis': typeof EngineerBasisRoute
  '/engineer/calculations': typeof EngineerCalculationsRoute
  '/engineer/codes': typeof EngineerCodesRoute
  '/engineer/compliance': typeof EngineerComplianceRoute
  '/engineer/integrity': typeof EngineerIntegrityRoute
  '/engineer/projects': typeof EngineerProjectsRoute
  '/engineer/reports': typeof EngineerReportsRoute
  '/engineer/review': typeof EngineerReviewRoute
  '/engineer/workflow': typeof EngineerWorkflowRoute
  '/engineer/': typeof EngineerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/engineer'
    | '/training'
    | '/engineer/audit'
    | '/engineer/basis'
    | '/engineer/calculations'
    | '/engineer/codes'
    | '/engineer/compliance'
    | '/engineer/integrity'
    | '/engineer/projects'
    | '/engineer/reports'
    | '/engineer/review'
    | '/engineer/workflow'
    | '/engineer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/training'
    | '/engineer/audit'
    | '/engineer/basis'
    | '/engineer/calculations'
    | '/engineer/codes'
    | '/engineer/compliance'
    | '/engineer/integrity'
    | '/engineer/projects'
    | '/engineer/reports'
    | '/engineer/review'
    | '/engineer/workflow'
    | '/engineer'
  id:
    | '__root__'
    | '/'
    | '/engineer'
    | '/training'
    | '/engineer/audit'
    | '/engineer/basis'
    | '/engineer/calculations'
    | '/engineer/codes'
    | '/engineer/compliance'
    | '/engineer/integrity'
    | '/engineer/projects'
    | '/engineer/reports'
    | '/engineer/review'
    | '/engineer/workflow'
    | '/engineer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngineerRoute: typeof EngineerRouteWithChildren
  TrainingRoute: typeof TrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer': {
      id: '/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof EngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/': {
      id: '/engineer/'
      path: '/'
      fullPath: '/engineer/'
      preLoaderRoute: typeof EngineerIndexRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/workflow': {
      id: '/engineer/workflow'
      path: '/workflow'
      fullPath: '/engineer/workflow'
      preLoaderRoute: typeof EngineerWorkflowRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/review': {
      id: '/engineer/review'
      path: '/review'
      fullPath: '/engineer/review'
      preLoaderRoute: typeof EngineerReviewRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/reports': {
      id: '/engineer/reports'
      path: '/reports'
      fullPath: '/engineer/reports'
      preLoaderRoute: typeof EngineerReportsRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/projects': {
      id: '/engineer/projects'
      path: '/projects'
      fullPath: '/engineer/projects'
      preLoaderRoute: typeof EngineerProjectsRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/integrity': {
      id: '/engineer/integrity'
      path: '/integrity'
      fullPath: '/engineer/integrity'
      preLoaderRoute: typeof EngineerIntegrityRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/compliance': {
      id: '/engineer/compliance'
      path: '/compliance'
      fullPath: '/engineer/compliance'
      preLoaderRoute: typeof EngineerComplianceRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/codes': {
      id: '/engineer/codes'
      path: '/codes'
      fullPath: '/engineer/codes'
      preLoaderRoute: typeof EngineerCodesRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/calculations': {
      id: '/engineer/calculations'
      path: '/calculations'
      fullPath: '/engineer/calculations'
      preLoaderRoute: typeof EngineerCalculationsRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/basis': {
      id: '/engineer/basis'
      path: '/basis'
      fullPath: '/engineer/basis'
      preLoaderRoute: typeof EngineerBasisRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/engineer/audit': {
      id: '/engineer/audit'
      path: '/audit'
      fullPath: '/engineer/audit'
      preLoaderRoute: typeof EngineerAuditRouteImport
      parentRoute: typeof EngineerRoute
    }
  }
}

interface EngineerRouteChildren {
  EngineerAuditRoute: typeof EngineerAuditRoute
  EngineerBasisRoute: typeof EngineerBasisRoute
  EngineerCalculationsRoute: typeof EngineerCalculationsRoute
  EngineerCodesRoute: typeof EngineerCodesRoute
  EngineerComplianceRoute: typeof EngineerComplianceRoute
  EngineerIntegrityRoute: typeof EngineerIntegrityRoute
  EngineerProjectsRoute: typeof EngineerProjectsRoute
  EngineerReportsRoute: typeof EngineerReportsRoute
  EngineerReviewRoute: typeof EngineerReviewRoute
  EngineerWorkflowRoute: typeof EngineerWorkflowRoute
  EngineerIndexRoute: typeof EngineerIndexRoute
}

const EngineerRouteChildren: EngineerRouteChildren = {
  EngineerAuditRoute: EngineerAuditRoute,
  EngineerBasisRoute: EngineerBasisRoute,
  EngineerCalculationsRoute: EngineerCalculationsRoute,
  EngineerCodesRoute: EngineerCodesRoute,
  EngineerComplianceRoute: EngineerComplianceRoute,
  EngineerIntegrityRoute: EngineerIntegrityRoute,
  EngineerProjectsRoute: EngineerProjectsRoute,
  EngineerReportsRoute: EngineerReportsRoute,
  EngineerReviewRoute: EngineerReviewRoute,
  EngineerWorkflowRoute: EngineerWorkflowRoute,
  EngineerIndexRoute: EngineerIndexRoute,
}

const EngineerRouteWithChildren = EngineerRoute._addFileChildren(
  EngineerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngineerRoute: EngineerRouteWithChildren,
  TrainingRoute: TrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
